### PR TITLE
feat: nicer error messages during development

### LINKED ISSUE #408: Errors while developing aren't very human-readable

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #408.

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

```
   Compiling numbat v1.11.0 (/home/hamir/numbat/numbat)
    Finished test [unoptimized + debuginfo] target(s) in 2.23s
     Running tests/interpreter.rs (target/debug/deps/interpreter-86e93d4b0103f0db)

running 1 test
thread 'test_algebra' panicked at numbat/tests/common.rs:27:21:
called `Result::unwrap()` on an `Err` value: ResolverError(ParseErrors([ParseError { kind: ExpectedThen, span: Span { start: SourceCodePositition { byte: 1029, line: 45, position: 22 }, end: SourceCodePositition { byte: 1054, line: 45, position: 47 }, code_source_id: 10 } }, ParseError { kind: ExpectedPrimary, span: Span { start: SourceCodePositition { byte: 1079, line: 46, position: 3 }, end: SourceCodePositition { byte: 1083, line: 46, position: 7 }, code_source_id: 10 } }]))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_algebra ... FAILED

failures:

failures:
    test_algebra

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 31 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p numbat --test interpreter`

 *  The terminal process "cargo 'test', '--package', 'numbat', '--test', 'interpreter', '--', 'test_algebra', '--exact', '--nocapture'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

image

**Comment by hamirmahal** [comment]
# With this change

```
   Compiling numbat v1.11.0 (/home/hamir/numbat/numbat)
    Finished test [unoptimized + debuginfo] target(s) in 2.14s
     Running tests/interpreter.rs (target/debug/deps/interpreter-86e93d4b0103f0db)

running 1 test
thread 'test_algebra' panicked at numbat/tests/common.rs:29:21:

--------------------------------------------------------------------------------
Error
Expected 'then' in if-then-else condition
Expected one of: number, identifier, parenthesized expression
--------------------------------------------------------------------------------

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_algebra ... FAILED

failures:

failures:
    test_algebra

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 31 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p numbat --test interpreter`

 *  The terminal process "cargo 'test', '--package', 'numbat', '--test', 'interpreter', '--', 'test_algebra', '--exact', '--nocapture'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

image

**Review by hamirmahal — COMMENTED** [review]
I'm definitely open to suggestions here. Anything that makes debugging easier is a win, I think.

**Comment by sharkdp** [comment]
Thank you!

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
