### PR TITLE
Add explicit use statement for non-prelude functions to examples

### LINKED ISSUE #602: Cannot find quadratic_equation on numbat.dev
image

### PR DESCRIPTION
**Pull request by Bzero**
Resolves #602.

### CODE REVIEW

**Review by sharkdp — APPROVED** [review]
Thank you!

**Comment by sharkdp** [comment]
Should we maybe add an additional `>>>` here?

image

**Comment by Bzero** [comment]
We can do that. Would you do it for all multi-line examples or only here with the `use` statements?

**Comment by Goju-Ryu** [comment]
I’m thinking all of them to make it clear what is input and what is output.

**Comment by sharkdp** [comment]
Just be aware that there might be multi-line *expressions* which should not be formatted this way. So something like
```
fn f(x) =
  x² + 1
```
should *not* be rendered as
```
>>> fn f(x) =
>>>  x² + 1
```
because it needs to be entered as a single line.

The easiest option might be to get rid of the `>>>` prompts all-together?

**Comment by sharkdp** [comment]
> I think the `>>> ` prompts help to distinguish in and output in the examples, especially for the many one-liners we have so I would prefer to keep them.

But we also have an indented equals sign for the outputs. So we would go from
```
>>> floor_in(m, 5.7 m)

    = 5 m    [Length]
```
to
```
floor_in(m, 5.7 m)

    = 5 m    [Length]
```

I don't really see a problem with that. I think I even prefer the latter one. Some users might not immediately understand that `>>>` is supposed to be a prompt.

**Comment by Bzero** [comment]
Yes that's true as well, I think it's fine to remove it then.

**Pull request merged**
