### PR TITLE
Plumbed spans through alias definitions, allowing for more precise er…

### LINKED ISSUE #570: Improve identifier clash errors when conflicting identifier is declared in `@aliases` decorator
i'm implementing https://github.com/sharkdp/numbat/issues/441, and there's a confusing error due to a conflict happening here:

```
@name("Malaysian ringgit")
@url("https://en.wikipedia.org/wiki/Malaysian_ringgit")
@aliases(malaysian_ringgits, MYR: short, myr, RM, rm)
unit malaysian_ringgit: Money = EUR / exchange_rate("MYR")
```

and the error:
```
>>> usd
error: identifier clash in definition
    ┌─ Module 'units::time', File <builtin>/modules/units/time.nbt:32:6
    │
 32 │ unit year: Time = 365.242_188_1 days
    │      ---- Previously defined here
    │
    ┌─ Module 'units::currencies', File <builtin>/modules/units/currencies.nbt:104:6
    │
104 │ unit malaysian_ringgit: Money = EUR / exchange_rate("MYR")
    │      ^^^^^^^^^^^^^^^^^ identifier is already in use
```

the conflict is between `myr` as `malaysian_ringgit` and `myr` as `milliyear`, but the error points to the primary identifiers `malaysian_ringgit` and `year` instead of the relevant aliases, and it also doesn't mention anything about the unit prefix

can this error be made clearer?

### PR DESCRIPTION
**Pull request by rben01**
…ror reporting of aliases conflicting with existing names

Simplified implementation of `name_and_aliases` (and `name_and_aliases_spans`, which returns spans); now only allocates once, and return a concrete `impl Iterator` (not `Box<dyn Iterator>`)

Closes #570 

Before:

```text
>>> @name("Malaysian ringgit")
@url("https://en.wikipedia.org/wiki/Malaysian_ringgit")
@aliases(malaysian_ringgits, MYR: short, myr, RM, rm)
unit malaysian_ringgit: Money = EUR / exchange_rate("MYR")
error: identifier clash in definition
   ┌─ Module 'units::time', File /opt/homebrew/Cellar/numbat/1.13.0/share/numbat/modules/units/time.nbt:32:6
   │
32 │ unit year: Time = 365.242_188_1 days
   │      ---- Previously defined here
   │
   ┌─ <input:7>:4:6
   │
 4 │ unit malaysian_ringgit: Money = EUR / exchange_rate("MYR")
   │      ^^^^^^^^^^^^^^^^^ identifier is already in use
```

After:

```text
>>> @name("Malaysian ringgit")
@url("https://en.wikipedia.org/wiki/Malaysian_ringgit")
@aliases(malaysian_ringgits, MYR: short, myr, RM, rm)
unit malaysian_ringgit: Money = EUR / exchange_rate("MYR")
error: identifier clash in definition
   ┌─ Module 'units::time', File <builtin>/modules/units/time.nbt:32:6
   │
32 │ unit year: Time = 365.242_188_1 days
   │      ---- Previously defined here
   │
   ┌─ <input:1>:3:42
   │
 3 │ @aliases(malaysian_ringgits, MYR: short, myr, RM, rm)
   │                                          ^^^ identifier is already in use
```

I debated whether to point the “previously defined here” error span not to `year` itself but to the alias responsible, `yr`, but thought that that was less helpful, as for more obscure aliases it won't be obvious what unit it is tied to (without using `info <alias>`). Also the line containing the alias often has lots of extraneous info such as other aliases or alias config. I think it's nicer to have the full chain of conflict laid out all the way back to the source, the original unit, which in theory should be quite obvious — everyone knows what `unit year: Time = 365.242_188_1 days` means.

### CODE REVIEW

**Comment by rben01** [comment]
I need help writing tests for this.

**Comment by rben01** [comment]
For future work it would be interesting to report all conflicting identifiers in one go. For instance, `rm` is also an existing unit (rontometre), but the error reporting bails after the first issue. This would require `NameResolutionError` to store a `Vec` or to be able to provide a `Vec<NameResolutionError>`.

**Comment by sharkdp** [comment]
I can help with creating tests for this (will take a few days though).

**Comment by sharkdp** [comment]
Sorry. I was interrupted while working on this. Will try to fix the tests on all platforms later today.

**Comment by sharkdp** [comment]
I reverted my changes. I tried to use `insta-cmd` to compare the output of the numbat program using `insta`. But I didn't manage to make it work cross-platform. And I somehow like the existing assert_cmd tests more. And the insta-cmd based tests required additional `cargo build` steps in CI / during local development. I'll merge this without a regression test for now.

**Pull request merged**
