### PR TITLE
Reduced allocations relating to `ast::Expression` + `typed_ast::Expression` and reduced allocations in `Transformer::transform_*` functions

### PR DESCRIPTION
**Pull request by rben01**

### CODE REVIEW

**Comment by rben01** [comment]
A single box should result in both fewer requests of the allocator and better cache locality when accessing that data, although I can't imagine it'd be a particularly large difference with the data we're working with here. Especially since who knows what optimizations the compiler is making — maybe if it sees three boxes side by side, it just places them next to each other in the heap anyway. I can revert that portion if you'd like because it probably makes very little difference.

**Comment by sharkdp** [comment]
> I can revert that portion if you'd like because it probably makes very little difference.

That would be great.

**Comment by sharkdp** [comment]
Thank you! There's one more conflict that needs to be fixed.

**Review by sharkdp — APPROVED** [review]
Thank you!

**Pull request merged**
