### PR TITLE
fix: layout shifting after terminal loads

### LINKED ISSUE #445: layout shifts after terminal loads

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #445.

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Preview

[Screencast from 06-03-2024 02:17:14 PM.webm](https://github.com/sharkdp/numbat/assets/43425812/11ac1405-9a60-47ad-8899-79a0bdda7375)

**Review by hamirmahal — COMMENTED** [review]
# Preview

[Screencast from 06-03-2024 02:17:14 PM.webm](https://github.com/sharkdp/numbat/assets/43425812/11ac1405-9a60-47ad-8899-79a0bdda7375)

**Comment by sharkdp** [comment]
Cool — I didn't know this technique. Can you please revert the autoformatting changes? It's difficult to review otherwise

**Comment by sharkdp** [comment]
I love it — thank you! Is this supported by major brower (version)s, or would we face compatibility problem with some older browsers?

**Comment by hamirmahal** [comment]
You're welcome! I don't think there's anything too fancy here; major browsers should support these changes.

I manually tested it on Firefox, and Brave (Chromium), without any issues, and it works on mobile Safari 15 and 17.

**Comment by sharkdp** [comment]
Awesome. The new version is live: https://numbat.dev/

**Pull request merged**
