### PR TITLE
style: status badge for `CICD` in `README.md`

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thanks. Can we move it down to the Development section? https://github.com/sharkdp/numbat?tab=readme-ov-file#development

**Comment by hamirmahal** [comment]
You're welcome!

**Review by hamirmahal — COMMENTED** [review]
# New preview

image

**Comment by hamirmahal** [comment]
Let me know if there's anything I should change.

**Review by sharkdp — APPROVED** [review]
Thanks

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
